FROM node:20-alpine

ENV NODE_ENV=development

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
COPY . .

RUN npm install --production --silent && mv node_modules ../
EXPOSE 3000

RUN chown -R node /usr/src/app
USER node
